- Coelhos/Rabbit(Estudo): Introdução ao Django Channels, Celery e Redis.md
- docs/sprints/sprint-2.md
**O que foi feito?**
- Foi adicionado  o Estudo sobre Django Channels, Celery e Redis como arquivo na pasta Coelhos.
> docs(mkdocs): Ajuste na pasta Coelhos

- Coelhos/Rabbit(Estudo): Introdução ao Django Channels, Celery e Redis.md
- README.md
- docs/Architecture.md
- docs/Task(Docs): Documentação para Padrões de Commit e Nomeação de Branches.md
- docs/sprints/sprint-2.md
- docs/sprints/sprint-3.md
**O que foi feito?**
- Foi desenvolvido e adicionado um diagrama de arquitetura para o sistema "AcheiUnB", documentando a estrutura de comunicação e dependência entre os principais componentes do sistema.
- Foi criado o arquivo `Architecture.md`, que fornece uma visão geral detalhada da arquitetura do projeto.
- Foram adicionados links ao sumário para melhorar a navegação no `README.md`, bem como foi feito o tópico com o link para o acesso do Protótipo de Arquitetura.
> Docs(Mkdocs): Realização do Protótipo de Arquitetura

- Coelhos/Rabbit(Estudo): Trazer soluções para a configuração dos ambientes
*Estudos de soluções para a configuração dos ambientes*
Definição de Linguagem e Versão;
Instrução para instalação de bibliotecas e dependências;
Configuração de variáveis de ambiente;
Instruções para conexões com Banco de Dados;
Configuração de ferramentas de desenvolvimento;
Ajuste de integração com Serviços externos.
> Create Rabbit(Estudo): Trazer soluções para a configuração dos ambientes

- docs/front-end/Visual-identity.md
- docs/sprints/sprint-3.md
- docs/sprints/sprint-4.md
**O que foi feito?**
- Foi criado o arquivo da Sprint 3 contendo as atas das reuniões.
> Docs(Mkdocs):  Criação do arquivo da Sprint 3

- .github/workflows/pipeline-ci.yaml
O que foi feito?
-  Criado o arquivo pipeline-ci.yaml
- Definido que os triggers serão em todo push e todo pull request na main
- O job test só foi definido até a parte de "clonagem do repositório", ainda não há ação de testagem programada de fato.
- Porém já foi adicionado o "esqueleto", de forma comentada, dos passos restantes de build, test e report. Com o ambiente a ser subido com Docker. Dessa forma a implementação final na 2ª parte da matéria será mais tranquila.
> Task(DevOps): Criação e implementação inicial do workflow de pipeline CI

- Coelhos/Rabbit(Estudo): Docker e Kubernetes.md
**O que foi feito?**
- Os Coelhos (estudos) sobre Docker e Kubernetes foram melhorados, adicionando mais informações importantes para o projeto.
- A possibilidade de implementação do Kubernetes no projeto foi estudada, sendo descartada, tendo em vista a baixa complexidade do projeto frente à alta capacidade, nesse caso, excessiva, do Kubernetes.
> Task(DevOps): Revisar Docker e Kubernetes e avaliar a possibilidade de implementação do Kubernetes no projeto

- README.md
Atualização do README do projeto AcheiUnB para incluir melhorias nas instruções de configuração e execução, além de detalhes mais claros sobre as funcionalidades e autenticação.
- Adicionados detalhes sobre a configuração e uso da autenticação via Microsoft OAuth.
- Atualizadas instruções para configuração de ambiente e dependências.
- Ajustado o sumário para refletir as seções adicionadas.
> Task(MKdocs): Ajuste no README

- docs/CODE_OF_CONDUCT.md
Este PR adiciona o documento de Código de Conduta (`CODE_OF_CONDUCT.md`) ao repositório, definindo as diretrizes e padrões de comportamento esperados para todos os membros e colaboradores do projeto.
---
- Adicionado o arquivo `CODE_OF_CONDUCT.md` contendo:
- Compromissos com um ambiente acolhedor e inclusivo.
- Exemplos de comportamentos aceitáveis e inaceitáveis.
- Processo de denúncia de violações e responsabilidades de aplicação.
- Diretrizes de impacto e consequências em caso de infrações.
- Adaptação baseada no [Contributor Covenant](https://www.contributor-covenant.org).
---
> Docs(CODE_OF_CONDUCT): Definindo o código de conduta do projeto

- README.md
Atualização do README do projeto AcheiUnB, adicionando o link correto para o direcionamento ao protótipo do projeto.
- Foi adicionado, na seção "Extra", mais especificamente, no subtópico "Protótipo", o link responsável por direcionar ao protótipo do projeto (AcheiUnB).
> Task(MKdocs): Adição do direcionamento ao protótipo do AcheiUnB no README

- docs/CONTRIBUTING.md
Este Pull Request adiciona o documento **Contributing Community Standards** para orientar colaboradores no projeto **AcheiUnB**. O documento inclui diretrizes detalhadas para:
- Relatar bugs e sugerir melhorias.
- Implementar novas funcionalidades e seguir boas práticas.
- Utilizar mensagens de commit no formato **Conventional Commits**.
- Criar e revisar Pull Requests de maneira eficiente.
O arquivo foi criado na pasta `docs/`, ao lado do `CODE_OF_CONDUCT.md`, e está referenciado no `README.md`.
---
---
> Task(Mkdocs): Adicionar documento Contributing 

- docs/sprints/sprint-0.md
- docs/sprints/sprint-1.md
- docs/sprints/sprint-2.md
- docs/sprints/sprint-3.md
- docs/sprints/sprint-4.md
- docs/sprints/sprint-5.md
- docs/sprints/sprint-6.md
- docs/sprints/sprint-template.md
Neste pull request, foi feita apenas o ajuste da listagem dos objetivos das Sprints.
Foi alterada a forma de listar os objetivos das Sprints na documentação.
> Task(MKdocs): Alteração da forma de listar os objetivos das Sprints

- Coelhos/Rabbit(Estudo): Comparativo de possíveis tecnologias de hospedagem para o projeto.md
Estudo sobre Heroku (plano para estudantes), AWS e Render.
Foi criado um arquivo para estudo sobre possíveis tecnologias de deploy para o projeto, focado em decidir qual tecnologia utilizar de fato, onde foi decidida a utilização do Render.
> Avaliar alternativas (caso não caiba a utilização do Heroku no projeto).

- API/AcheiUnB/settings.py
- API/users/apps.py
- API/users/serializers.py
- API/users/signals.py
- API/users/tests.py
- API/users/views.py
Este PR refatora a funcionalidade de edição de itens para garantir uma manipulação segura e consistente de imagens. Durante a edição, agora é possível:
- Adicionar novas imagens respeitando o limite máximo de 2 imagens por item.
- Remover imagens existentes, identificadas por seus IDs.
- Garantir que imagens excluídas do banco de dados sejam automaticamente removidas do Cloudinary.
Além disso, IDs das imagens relacionadas aos itens agora são retornados na resposta da API para facilitar a organização e manipulação no front-end.
---
- **Atualização do `ItemSerializer`:**
- Adicionado suporte para adição de novas imagens durante a edição, com validação do limite máximo.
- Adicionado suporte para remoção de imagens existentes, identificadas por seus IDs.
- IDs das imagens relacionadas …
> Refactor(Item): Verificado a edição de itens e Implementado a manipulação e exclusão segura de imagens por parte dos usuários

- web/src/views/User.vue
Este PR *implementa a página de usuário* no projeto *AcheiUnB*, permitindo que o usuário visualize suas informações pessoais e tenha uma experiência mais integrada ao sistema.
A tela de usuário agora permite:
- Exibir *nome, e-mail e matrícula* do usuário autenticado.
- Carregar a *foto do usuário* diretamente da API, caso exista.
- Exibir um *fundo cinza com "Foto Padrão"* caso o usuário não tenha uma foto cadastrada.
- Criado o arquivo User.vue para exibir os dados do usuário logado.
- Implementada a interface utilizando *Vue.js + TailwindCSS* para garantir um design moderno e responsivo.
- Criado um layout *simples e funcional*, mantendo a identidade visual do AcheiUnB.
- Adicionada requisição GET para o endpoint /api/auth/user/ para buscar os dados do usuário autenticado.
- *Nome:* …
> Feat(user): Criação da página de usuário

- API/users/templates/emails/welcome.html
- web/src/views/About.vue
- web/src/views/User.vue
> Task(front): Criação do botão "Como Contribuir?", ajustes na tela de usuário e melhoria no email de boas-vindas

- web/src/views/Found.vue
- web/src/views/Lost.vue
Design dos botões de paginação
> feat(fornt): design dos botões de paginação

- web/src/views/Found.vue
Correção do método de paginação
> fix(front): Paginação

- web/src/views/Lost.vue
Inlcui correção da paginção do página de Lost
> 195/front/design dos botões de paginação

- web/src/views/ListItem.vue
Este PR resolve problemas na listagem de imagens na página do item e ajusta o alinhamento do texto para melhorar a apresentação visual da interface.
Agora, a interface:
- Exibe corretamente a **imagem do item** na página de listagem.
- Alinha o **texto à esquerda**, seguindo um layout mais intuitivo.
---
- Ajustado o componente `ItemList.vue` para garantir que as imagens dos itens sejam carregadas corretamente.
- Implementada uma lógica de fallback para **exibir uma imagem padrão** caso um item não possua foto cadastrada.
- Melhorado o tratamento de erro para evitar que imagens quebradas afetem a renderização da interface.
- Modificado o layout para que as descrições dos itens fiquem **alinhadas à esquerda**.
- Atualizado o uso do TailwindCSS para garantir uma disposição visual mais …
> Fix(item): Corrigindo bugs da listagem do item

- web/src/assets/icons/user.svg
- web/src/components/Chatroom.vue
- web/src/views/Chats.vue
- web/src/views/Message.vue
- web/src/views/User.vue
Criação da tela de chat
Criação a tela de chat, que pode ser acessada a partir do menu principal (parte inferior da tela), clicando no ícone de mensagens.
Na tela, são listadas as chatrooms em que o usuário logado está envolvido. Ao clicar, é direcionado paraa página de conversa com o outro usuário.
> feat(front): Criação da tela de chat

- API/users/urls.py
- web/src/assets/main.css
- web/src/components/Empty-State-User.vue
- web/src/views/ListItem.vue
Correção de diversos erros.
Corrige erros de arquivos que impediam a main de rodar. Corrige lógica de botões da listagem de itens.
> fix(geral): corrige erros gerais de arquivos e componentes

- API/AcheiUnB/settings.py
- API/AcheiUnB/urls.py
- API/chat/views.py
- API/requirements.txt
- API/users/views.py
- Implementação da documentação das APIs do **AcheiUnB** utilizando `drf-yasg`.  
- Adicionada documentação para os endpoints de **usuários, itens, categorias, locais e mensagens**.  
- Correção do erro de `swagger_auto_schema` duplicado na `ClearChatsView`.  
- Ajustes no `urls.py` do app **chat** para garantir que a documentação Swagger funcione corretamente.  
- Testes realizados e Swagger disponível em **`/swagger/`** e **ReDoc em `/redoc/`**.  
---
> Task(docs): Documentado todas as APIs
